# Automatically updated by the winget bot at 2024/Apr/17
# yaml-language-server: $schema=https://aka.ms/winget-manifest.singleton.1.7.0.schema.json

PackageIdentifier: Logitech.LGH
Publisher: Logitech
PackageName: Logitech Gaming Hub
Author: Logitech
ShortDescription: Customize Logitech G gaming mice, keyboards, headsets, speakers, and other devices
Moniker: lghub
Tags:
- mouse
- keyboard
- headset
- driver
PackageUrl: https://gaming.logicool.co.jp/en-US/innovation/g-hub.html
License: Copyright (c) Logitech, Inc. 2020
LicenseUrl: https://secure.logitech.com/en-us/footer/terms-of-use
MinimumOSVersion: 10.0.0.0
PackageVersion: 2024.3.3733
InstallerType: exe
Installers:
- InstallerSwitches:
    Silent: ''
    SilentWithProgress: ''
  Architecture: x64
  InstallerUrl: https://download01.logi.com/web/ftp/pub/techsupport/gaming/lghub_installer.exe
  InstallerSha256: E13D766BCF9FDE512AC9FE904BA4AB1B1F39303F7C8BB76028C7FB5A0C99E638
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.7.0
