PackageIdentifier: 7zip.7zip
PackageName: 7Zip
Moniker: 7zip
PackageVersion: 19.0.0
Publisher: 7zip
Author: 7zip
License: MIT License
LicenseUrl: https://github.com/microsoft/msix-packaging/blob/master/LICENSE
MinimumOSVersion: 10.0.0.0
PackageUrl: https://www.7-zip.org/
Tags:
- 7zip
- compression
- file compression
- utility
- tool
- zip
InstallerType: msi
Installers:
- Architecture: x64
  InstallerUrl: https://stpkgmanvalwestustest.blob.core.windows.net/test-installers/AtomSetup-x64.exe
  InstallerSha256: 09eebc165474969deea115a3cb6a3b88ca206e2c65975e76e6b7d891d1d6e648
ShortDescription: 7zip.7zip
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.5.0
