# Automatically updated by the winget bot at 2024/May/30
# yaml-language-server: $schema=https://aka.ms/winget-manifest.singleton.1.7.0.schema.json

PackageIdentifier: Logitech.LGH
Publisher: Logitech
PackageName: Logitech Gaming Hub
Author: Logitech
ShortDescription: Customize Logitech G gaming mice, keyboards, headsets, speakers, and other devices
Moniker: lghub
Tags:
- mouse
- keyboard
- headset
- driver
PackageUrl: https://gaming.logicool.co.jp/en-US/innovation/g-hub.html
License: Copyright (c) Logitech, Inc. 2020
LicenseUrl: https://secure.logitech.com/en-us/footer/terms-of-use
MinimumOSVersion: 10.0.0.0
PackageVersion: 2024.4.2095
InstallerType: exe
Installers:
- InstallerSwitches:
    Silent: ''
    SilentWithProgress: ''
  Architecture: x64
  InstallerUrl: https://download01.logi.com/web/ftp/pub/techsupport/gaming/lghub_installer.exe
  InstallerSha256: 29863A90FFD7D97587A4C72844029F8D8A446C755F2623D82A086705159B66C9
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.7.0
